Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-07, with the labels that each got.

#807 Ensures a single database connection is used.
  src/main/java/world/bentobox/bentobox/database/Database.java
  src/main/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabaseConnector.java
  src/test/java/world/bentobox/bentobox/database/DatabaseTest.java
Labels: Critical, Status: Completed, Type: Bug

#811 More async stuff & WorldEdit integration: Blueprint ClipboardFormat
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/blueprints/worldedit/BlueprintClipboardFormat.java
  src/main/java/world/bentobox/bentobox/blueprints/worldedit/BlueprintClipboardReader.java
  src/main/java/world/bentobox/bentobox/blueprints/worldedit/BlueprintClipboardWriter.java
  src/main/java/world/bentobox/bentobox/blueprints/worldedit/BlueprintSchematicConverter.java
  src/main/java/world/bentobox/bentobox/hooks/WorldEditHook.java
  src/main/java/world/bentobox/bentobox/managers/BlueprintsManager.java
  src/main/java/world/bentobox/bentobox/schems/SchemToBlueprint.java
Labels: Status: Completed, Type: Enhancement

#822 Removes nether trees.
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/listeners/NetherTreesListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/test/java/world/bentobox/bentobox/listeners/NetherTreesListenerTest.java
  src/test/java/world/bentobox/bentobox/managers/IslandWorldManagerTest.java
  src/test/java/world/bentobox/bentobox/managers/PlayersManagerTest.java
Labels: Status: Completed, Type: Enhancement

#817 API addition - adds reset deaths on new island
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIsland.java
Labels: Status: Completed, Type: Enhancement

#821 Adds a cooldown API for flags.
  src/main/java/world/bentobox/bentobox/api/flags/Flag.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/IslandToggleClick.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/database/objects/adapters/FlagSerializer3.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandlerTest.java
Labels: Status: Completed, Type: Enhancement

#823 Makes command ranks a protection setting
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandBanCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandExpelCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandUnbanCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamPromoteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamUncoopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamUntrustCommand.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandCycleClick.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandRankClickListener.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/resources/config.yml
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandBanCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandExpelCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandUnbanCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamUncoopCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamUntrustCommandTest.java
Labels: Type: Enhancement

#827 Makes JSON database async for saving and deletion
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
Labels: Status: Completed, Type: Enhancement

#829 Adds admin purge command.
  src/main/java/world/bentobox/bentobox/api/commands/admin/purge/AdminPurgeCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/purge/AdminPurgeStopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/purge/AdminPurgeUnownedCommand.java
  src/main/resources/locales/en-US.yml
Labels: Status: Completed, Type: Enhancement

#831 Database abstraction
  src/main/java/world/bentobox/bentobox/database/AbstractDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/DatabaseSetup.java
  src/main/java/world/bentobox/bentobox/database/json/AbstractJSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mysql/package-info.java
  src/main/java/world/bentobox/bentobox/database/postgresql/PostgreSQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/postgresql/PostgreSQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLConfiguration.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/package-info.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/package-info.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/package-info.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/package-info.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2PostgreSQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2SQLiteDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/MariaDB2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/MySQL2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/PostgreSQL2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/SQLite2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2SQLiteDatabase.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/test/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseConnectorTest.java
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandlerTest.java
Labels: Status: Completed, Type: Enhancement

#834 Fixes owner being allowed to demote himself
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamPromoteCommand.java
  src/main/resources/locales/en-US.yml
Labels: Critical, Type: Bug

#835 Corrects message string for demote command
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamPromoteCommand.java
Labels: Status: Completed, Type: Bug

#832 Update lv-LV.yml
  src/main/resources/locales/lv-LV.yml
Labels: Status: Completed, Type: Enhancement

#850 Implements an island reservation system using the admin register command
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandCreateCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandGoCommand.java
  src/main/java/world/bentobox/bentobox/api/events/island/IslandEvent.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIsland.java
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandCreateCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandGoCommandTest.java
Labels: Status: Completed, Type: Enhancement

#861 Implements #get and #has - PlayersOnIsland method
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
Labels: Status: Completed, Type: Enhancement

#866 Fix compile failure with PR #861
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
Labels: Critical, Status: Completed, Type: Bug
