Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-09, with the labels that each got.

#929 Updated es translation
  src/main/resources/locales/es.yml
Labels: Status: Done, Type: Enhancement

#935 Update latvian translation
  src/main/resources/locales/lv.yml
Labels: Type: Enhancement

#939 Easier addon getter by their name
  src/main/java/world/bentobox/bentobox/api/commands/CompositeCommand.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
Labels: Status: Done, Type: Enhancement

#941 Fixed HeadGetter overwriting item amount
  src/main/java/world/bentobox/bentobox/util/heads/HeadGetter.java
Labels: Status: Done, Type: Bug

#957 Prevent to set null as icon in PanelItems.
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelItemBuilder.java
Labels: Important, Status: Done, Type: Bug

#956 Add missing permission prefixes to expel command.
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandBanCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandExpelCommand.java
Labels: Status: Done, Type: Bug
