Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-05, with the labels that each got.

#648 Rewrote chunk deletion
  src/main/java/world/bentobox/bentobox/api/addons/GameModeAddon.java
  src/main/java/world/bentobox/bentobox/database/objects/IslandDeletion.java
  src/main/java/world/bentobox/bentobox/util/DeleteIslandChunks.java
  src/main/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleport.java
Labels: Status: Accepted, Type: Bug, Type: Enhancement

#660 Add color translation for Panel and PanelItem names.
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelBuilder.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelItemBuilder.java
Labels: Status: Accepted, Type: Enhancement

#661 Enables game mode addons to run as the only world
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/api/addons/Addon.java
  src/main/java/world/bentobox/bentobox/api/commands/CompositeCommand.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/main/resources/plugin.yml
Labels: Status: Accepted, Type: Enhancement

#666 Fixes incorrect sethome if an island was locked
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommand.java
Labels: Status: Accepted, Type: Bug

#662 Database transition
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/api/configuration/ConfigObject.java
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/commands/BentoBoxCommand.java
  src/main/java/world/bentobox/bentobox/commands/BentoBoxMigrateCommand.java
  src/main/java/world/bentobox/bentobox/database/AbstractDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/DatabaseSetup.java
  src/main/java/world/bentobox/bentobox/database/json/AbstractJSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/MySQL2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/TransitionDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/yaml/ConfigHandler.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/main/resources/config.yml
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/managers/IslandsManagerTest.java
  src/test/java/world/bentobox/bentobox/managers/PlayersManagerTest.java
Labels: Status: Accepted, Type: Enhancement

#655 Create Latvian language file.
  src/main/resources/locales/lv-LV.yml
Labels: Status: Accepted, Type: Enhancement

#677 Update BentoBox pom.
  pom.xml
  src/main/resources/plugin.yml
Labels: Status: Completed, Type: Enhancement

#678 Append build number to builds compiled by the CI
  pom.xml
Labels: Status: Completed, Type: Enhancement

#684 Moved less intensive checks in front when blocking end dragon spawn
  src/main/java/world/bentobox/bentobox/listeners/BlockEndDragon.java
Labels: Status: Completed, Type: Enhancement

#686 Load blueprints with non-lowercase names
  src/main/java/world/bentobox/bentobox/managers/BlueprintsManager.java
Labels: Status: Completed, Type: Enhancement

#691 Implement Blueprint Bundles GUI
  pom.xml
  src/main/java/world/bentobox/bentobox/api/commands/admin/blueprints/AdminBlueprintCommand.java
  src/main/java/world/bentobox/bentobox/blueprints/Blueprint.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/DescriptionPrompt.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/DescriptionSuccessPrompt.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/NameConversationPrefix.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/NamePrompt.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/NameSuccessPrompt.java
  src/main/java/world/bentobox/bentobox/blueprints/dataobjects/BlueprintBundle.java
  src/main/java/world/bentobox/bentobox/managers/BlueprintsManager.java
  src/main/java/world/bentobox/bentobox/panels/BlueprintManagementPanel.java
  src/main/java/world/bentobox/bentobox/panels/BundleManagementPanel.java
  src/main/java/world/bentobox/bentobox/panels/IslandCreationPanel.java
  src/main/java/world/bentobox/bentobox/panels/ManagementPanel.java
Labels: Type: Enhancement

#692 Remove unnecessary checks in IslandsManager and IslandWorldManager.
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
Labels: Status: Completed, Type: Enhancement

#697 Add ability to Register Flag From Addon class
  src/main/java/world/bentobox/bentobox/api/addons/Addon.java
Labels: Status: Completed, Type: Enhancement

#698 Fixed some code smells
  src/main/java/world/bentobox/bentobox/api/addons/AddonClassLoader.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/resets/AdminResetsResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandNearCommand.java
  src/main/java/world/bentobox/bentobox/blueprints/Blueprint.java
  src/main/java/world/bentobox/bentobox/blueprints/BlueprintClipboard.java
  src/main/java/world/bentobox/bentobox/blueprints/BlueprintPaster.java
  src/main/java/world/bentobox/bentobox/blueprints/conversation/DescriptionPrompt.java
  src/main/java/world/bentobox/bentobox/blueprints/dataobjects/BlueprintBundle.java
  src/main/java/world/bentobox/bentobox/database/json/BentoboxTypeAdapterFactory.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/json/adapters/ItemStackTypeAdapter.java
  src/main/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/objects/IslandDeletion.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandCycleClick.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandRankClickListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoLimitClickListener.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/main/java/world/bentobox/bentobox/managers/BlueprintsManager.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/LocalesManager.java
  src/main/java/world/bentobox/bentobox/panels/BlueprintManagementPanel.java
  src/main/java/world/bentobox/bentobox/panels/BundleManagementPanel.java
  src/main/java/world/bentobox/bentobox/schems/Converter.java
  src/main/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleport.java
Labels: Status: Completed, Type: Bug
