Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-03, with the labels that each got.

#587 Updated to use cleaner code
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/IslandRespawnListener.java
Labels: Status: Accepted, Type: Enhancement

#590 Players with "admin.noban" permission can't be banned
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandBanCommand.java
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#596 Improve BentoBox pom.
  pom.xml
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#600 Delete command fix
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminDeleteCommand.java
  src/main/resources/locales/en-US.yml
  src/main/resources/locales/ja-JP.yml
  src/main/resources/locales/pl-PL.yml
  src/main/resources/locales/vi-VN.yml
  src/main/resources/locales/zh-CN.yml
  src/main/resources/locales/zh-HK.yml
Labels: Priority: Medium, Status: Accepted, Type: Bug

#602 Handle Mooshroom "milking"
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/BucketListener.java
Labels: Priority: Medium, Status: Accepted, Type: Bug

#595 Fix Phantoms
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/HurtingListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/settings/MobSpawnListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/util/Util.java
Labels: Priority: Medium, Status: Accepted, Type: Bug

#605 Async delete
  src/main/java/world/bentobox/bentobox/database/AbstractDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/Database.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/island/IslandCache.java
Labels: Priority: Critical, Status: Accepted, Type: Bug

#615 Saves world settings to config.yml when they are changed mid-game.
  src/main/java/world/bentobox/bentobox/api/addons/GameModeAddon.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClick.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoLimitClickListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListener.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClickTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListenerTest.java
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#617 Flag visibility
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/api/flags/Flag.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/CycleClick.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/IslandToggleClick.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClick.java
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelBuilder.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelItemBuilder.java
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/main/java/world/bentobox/bentobox/panels/SettingsPanel.java
  src/test/java/world/bentobox/bentobox/api/flags/FlagTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/CycleClickTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/IslandToggleClickTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClickTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/settings/PVPListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListenerTest.java
  src/test/java/world/bentobox/bentobox/managers/IslandWorldManagerTest.java
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#616 Auto adds default placeholders for GameModeAddons
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/api/placeholders/placeholderapi/BasicPlaceholderExpansion.java
  src/main/java/world/bentobox/bentobox/hooks/PlaceholderAPIHook.java
  src/main/java/world/bentobox/bentobox/lists/GameModePlaceholders.java
  src/main/java/world/bentobox/bentobox/managers/GameModePlaceholderManager.java
  src/main/java/world/bentobox/bentobox/managers/PlaceholdersManager.java
  src/test/java/world/bentobox/bentobox/managers/AddonsManagerTest.java
  src/test/java/world/bentobox/bentobox/managers/GameModePlaceholderManagerTest.java
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#620 add akarin a Async paper fork and glowstone
  src/main/java/world/bentobox/bentobox/versions/ServerCompatibility.java
Labels: Priority: Low, Status: Accepted, Type: Enhancement
