Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-02, with the labels that each got.

#527 Add island.team.promote permission
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamPromoteCommand.java
Labels: Tweak :desktop_computer:

#565 Minecart protection flags.
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/BlockInteractionListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/EntityInteractListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/InventoryListener.java
Labels: Priority: High, Status: Completed, Type: Enhancement

#567 Fix issue when Owners could not kick team members
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
Labels: Priority: Medium, Status: Completed, Type: Bug

#569 Fix issue where TeamMembers could not set island home.
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandSethomeCommand.java
Labels: Priority: High, Status: Completed, Type: Bug

#564 Fix issue with offline players that kept inventory
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/database/objects/Players.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
Labels: Priority: High, Status: Completed, Type: Bug

#574 Fixes IllegalArgumentException in VaultHook by adding the ability to get a User instance from an OfflinePlayer
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/user/User.java
  src/main/java/world/bentobox/bentobox/hooks/VaultHook.java
Labels: Priority: Medium, Status: Completed, Type: Enhancement
