Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-06, with the labels that each got.

#721 Update Latvian language file
  src/main/resources/locales/lv-LV.yml
Labels: Status: Completed, Type: Enhancement

#723 Disable physics updating for exit portal
  src/main/java/world/bentobox/bentobox/listeners/BlockEndDragon.java
Labels: Status: Completed, Type: Enhancement

#724 Added it-IT.yml
  src/main/resources/locales/it-IT.yml
Labels: Status: Completed, Type: Enhancement

#714 Added Island#hasNetherIsland() & Island#hasEndIsland()
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
Labels: Status: Completed, Type: Enhancement

#730 Improved handling of click events for Panels
  src/main/java/world/bentobox/bentobox/listeners/PanelListenerManager.java
Labels: Status: Completed, Type: Bug

#743 Close all panels on plugin disable
  src/main/java/world/bentobox/bentobox/commands/BentoBoxReloadCommand.java
  src/main/java/world/bentobox/bentobox/listeners/PanelListenerManager.java
  src/test/java/world/bentobox/bentobox/commands/BentoBoxReloadCommandTest.java
Labels: Status: Need review, Type: Enhancement

#713 Creating end/nether islands on first join to dimension
  src/main/java/world/bentobox/bentobox/listeners/PortalTeleportationListener.java
Labels: Really Rather Important, Status: Need review, Type: Enhancement

#761 Secured the handling of InventoryClickEvent for panels
  src/main/java/world/bentobox/bentobox/listeners/PanelListenerManager.java
Labels: 1.14, Status: Completed, Type: Bug

#763 Added ability to explicitly define asynchronous PremadeEvent
  src/main/java/world/bentobox/bentobox/api/events/PremadeEvent.java
Labels: Status: Completed, Type: Enhancement

#764 Fixed NPE in PanelListenerManager tests
  src/test/java/world/bentobox/bentobox/listeners/PanelListenerManagerTest.java
Labels: Status: Completed, Type: Enhancement

#769 Fixed ender dragon issue in 1.14+
  src/main/java/world/bentobox/bentobox/listeners/BlockEndDragon.java
Labels: 1.14, Status: Completed, Type: Bug

#772 Implements new call API for commands
  src/main/java/world/bentobox/bentobox/api/commands/CompositeCommand.java
Labels: Status: Completed, Type: Enhancement

#775 Automatically provides key-value pairs for PremadeEvents
  src/main/java/world/bentobox/bentobox/api/events/BentoBoxEvent.java
  src/main/java/world/bentobox/bentobox/api/events/PremadeEvent.java
  src/main/java/world/bentobox/bentobox/api/events/addon/AddonBaseEvent.java
Labels: Type: Enhancement

#782 Improved CleanSuperFlat check
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/CleanSuperFlatListener.java
Labels: Status: Completed, Type: Bug

#792 Fix error on bentobox version check
  src/main/java/world/bentobox/bentobox/commands/BentoBoxVersionCommand.java
Labels: Status: Completed, Type: Bug

#791 Added SQLite database
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/database/DatabaseSetup.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabase.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sqlite/SQLiteDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sqlite/package-info.java
  src/main/resources/config.yml
  src/test/java/world/bentobox/bentobox/database/mariadb/MariaDBDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseConnectorTest.java
  src/test/java/world/bentobox/bentobox/database/mysql/MySQLDatabaseHandlerTest.java
Labels: Status: Completed, Type: Enhancement

#794 Added more transition databases
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/database/DatabaseSetup.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2MongoDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Json2SQLiteDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/MariaDB2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/MongoDB2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/SQLite2JsonDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2MongoDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/transition/Yaml2SQLiteDatabase.java
  src/main/resources/config.yml
Labels: Status: Completed, Type: Enhancement
