Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-10, with the labels that each got.

#971 Adds invites to trust and coop
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/Invite.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteRejectCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommand.java
  src/main/resources/config.yml
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommandTest.java
Labels: Status: Done, Type: Enhancement

#984 Allows customizing where islands are created
  src/main/java/world/bentobox/bentobox/managers/island/DefaultNewIslandLocationStrategy.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIsland.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIslandLocationStrategy.java
Labels: Status: Done, Type: Enhancement

#986 Add cake protection flag
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/BlockInteractionListener.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1004 Set the bentobox.version permission default value to op
  src/main/resources/plugin.yml
Labels: Status: Done, Type: Bug

#1001 Generalize protection messages
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1007 Added ability to have player heads with custom name
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelItemBuilder.java
  src/main/java/world/bentobox/bentobox/util/heads/HeadGetter.java
Labels: Status: Done, Type: Bug, Type: Enhancement
