Repository BentoBoxWorld/BentoBox, pull requests merged in 2019-08, with the labels that each got.

#857 Tab panels
  src/main/java/world/bentobox/bentobox/api/commands/DelayedTeleportCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/flags/Flag.java
  src/main/java/world/bentobox/bentobox/api/flags/FlagListener.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/CycleClick.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/IslandToggleClick.java
  src/main/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClick.java
  src/main/java/world/bentobox/bentobox/api/panels/Panel.java
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/api/panels/PanelListener.java
  src/main/java/world/bentobox/bentobox/api/panels/Tab.java
  src/main/java/world/bentobox/bentobox/api/panels/TabbedPanel.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelBuilder.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/TabbedPanelBuilder.java
  src/main/java/world/bentobox/bentobox/listeners/PanelListenerManager.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/CleanSuperFlatListener.java
  src/main/java/world/bentobox/bentobox/panels/SettingsPanel.java
  src/main/java/world/bentobox/bentobox/panels/settings/SettingsTab.java
  src/main/java/world/bentobox/bentobox/panels/settings/WorldDefaultSettingsTab.java
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/api/flags/FlagTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/CycleClickTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/IslandToggleClickTest.java
  src/test/java/world/bentobox/bentobox/api/flags/clicklisteners/WorldToggleClickTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/settings/PVPListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/ChestDamageListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/CleanSuperFlatListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/EnderChestListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/EndermanListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/ItemFrameListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/LiquidsFlowingOutListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/OfflineGrowthListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/OfflineRedstoneListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/RemoveMobsListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/TreesGrowingOutsideRangeListenerTest.java
Labels: Status: Completed, Status: Need review, Type: Enhancement

#888 Implements Basic/Advanced/Expert settings panels
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/flags/Flag.java
  src/main/java/world/bentobox/bentobox/api/panels/Tab.java
  src/main/java/world/bentobox/bentobox/api/panels/TabbedPanel.java
  src/main/java/world/bentobox/bentobox/database/objects/Players.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/java/world/bentobox/bentobox/managers/PlayersManager.java
  src/main/java/world/bentobox/bentobox/panels/settings/SettingsTab.java
  src/main/resources/locales/en-US.yml
  src/main/resources/locales/fr-FR.yml
Labels: Status: Completed, Type: Enhancement

#892 Update lv-LV.yml
  src/main/resources/locales/lv-LV.yml
Labels: Status: Completed, Type: Enhancement

#913 Disable physic applying on regeneration
  src/main/java/world/bentobox/bentobox/util/DeleteIslandChunks.java
Labels: Status: Completed, Type: Enhancement

#917 Add multiple different types of panel.
  src/main/java/world/bentobox/bentobox/api/panels/Panel.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelBuilder.java
Labels: Status: Completed, Type: Enhancement

#919 1.14.4
  pom.xml
  src/main/java/world/bentobox/bentobox/blueprints/BlueprintPaster.java
  src/main/java/world/bentobox/bentobox/database/json/adapters/ItemStackTypeAdapter.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/settings/MobSpawnListener.java
  src/main/java/world/bentobox/bentobox/util/ItemParser.java
  src/main/java/world/bentobox/bentobox/versions/ServerCompatibility.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommandTest.java
  src/test/java/world/bentobox/bentobox/api/flags/FlagTest.java
  src/test/java/world/bentobox/bentobox/database/json/adapters/ItemStackTypeAdapterTest.java
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseConnectorTest.java
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/listeners/PanelListenerManagerTest.java
  src/test/java/world/bentobox/bentobox/listeners/PortalTeleportationListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/BreakBlocksListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/BucketListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/InventoryListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/PhysicalInteractionListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/PlaceBlocksListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/TNTListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/settings/MobSpawnListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/EnderChestListenerTest.java
  src/test/java/world/bentobox/bentobox/managers/IslandsManagerTest.java
Labels: 1.14, Status: Done, Type: Enhancement
