Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-10, with the labels that each got.

#1514 Gamemode replacement for placeholders
  src/main/java/world/bentobox/bentobox/api/placeholders/placeholderapi/BasicPlaceholderExpansion.java
  src/main/java/world/bentobox/bentobox/api/placeholders/placeholderapi/BentoBoxPlaceholderExpansion.java
  src/main/java/world/bentobox/bentobox/hooks/placeholders/PlaceholderAPIHook.java
  src/test/java/world/bentobox/bentobox/hooks/placeholders/PlaceholderAPIHookTest.java
Labels: Type: Enhancement

#1511 Portuguese localization
  src/main/resources/locales/pt.yml
  src/main/resources/locales/pt_BR.yml
Labels: Status: Under investigation, Type: Enhancement

#1541 Add addon version in enabling statement
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
Labels: Type: Enhancement

#1542 Fix an issue when CommandEvents were never called
  src/main/java/world/bentobox/bentobox/api/events/command/CommandEvent.java
Labels: Type: Bug

#1539 Enables nether and end teleporting even if they are disabled by server
  src/main/java/world/bentobox/bentobox/listeners/PortalTeleportationListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/PortalListener.java
  src/test/java/world/bentobox/bentobox/listeners/PortalTeleportationListenerTest.java
Labels: 1.16, Type: Enhancement

#1448 Adding world specification on methods of Vault Hook
  src/main/java/world/bentobox/bentobox/hooks/VaultHook.java
Labels: Status: Need review, Type: Enhancement, api
