Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-11, with the labels that each got.

#1558 Stops async db saving on shutdown. Adds JSON backup.
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/database/AbstractDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/listeners/PortalTeleportationListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/PlayersManager.java
  src/main/java/world/bentobox/bentobox/util/Util.java
  src/test/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/util/UtilTest.java
Labels: Status: Need review

#1574 Fixed parsing [gamemode] in placeholders
  src/main/java/world/bentobox/bentobox/hooks/placeholders/PlaceholderAPIHook.java
Labels: Status: Done, Type: Bug

#1578 Limit island/player saves per tick
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/PlayersManager.java
Labels: Status: Need review, Type: Bug
