Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-01, with the labels that each got.

#1111 Fix for double calling of events
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetrankCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetspawnCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminUnregisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamDisbandCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamSetownerCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteRejectCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamLeaveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamSetownerCommand.java
  src/main/java/world/bentobox/bentobox/api/events/addon/AddonEvent.java
  src/main/java/world/bentobox/bentobox/api/events/team/TeamEvent.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminSetrankCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommandTest.java
Labels: Type: Bug, Type: Enhancement, api

#1114 Changed Webtool link old to new
  README.md
Labels: Status: Done, Type: Documentation

#1112 Compiling under Java 9+
  .travis.yml
  pom.xml
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseConnectorTest.java
Labels: Status: Done, Type: Enhancement

#1141 Puts the GSON serialization on main thread.
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseHandler.java
Labels: Type: Enhancement

#1109 Add new IslandEvent: IslandProtectionRangeChange
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeRemoveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeSetCommand.java
  src/main/java/world/bentobox/bentobox/api/events/island/IslandEvent.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
Labels: Status: Done, Type: Enhancement, api

#1142 Postgres implementation
  pom.xml
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseHandler.java
  src/main/resources/config.yml
Labels: Status: Done, Type: Enhancement

#1146 Adds explicit permissions to team commands
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteRejectCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamLeaveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamSetownerCommand.java
Labels: Status: Done, Type: Enhancement

#1153 Added ExtraMobs to the list
  ADDON.md
Labels: Status: Done, Type: Documentation
