Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-02, with the labels that each got.

#1167 Remove Bank from ADDON.md as it is not available yet
  ADDON.md
Labels: Status: Done, Type: Documentation

#1155 Added LIMIT_MOBS flag (WORLD_SETTING)
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/MobLimitClickListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/LimitMobsListener.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/main/resources/locales/en-US.yml
Labels: Status: Need review, Type: Enhancement

#1179 Added #getOldIsland() in island reset-related events
  src/main/java/world/bentobox/bentobox/api/events/island/IslandEvent.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIsland.java
Labels: Status: Done, Type: Enhancement, api
