Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-08, with the labels that each got.

#1496 Added Visit and Upgrades to the ADDON.md list
  ADDON.md
Labels: Status: Done, Type: Documentation

#1500 Small fix in cs.yml
  src/main/resources/locales/cs.yml
Labels: Status: Done, Type: Enhancement

#1499 Added support to hide Vanished players from Teams
  pom.xml
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCommand.java
  src/main/resources/locales/en-US.yml
Labels: Status: Need review, Type: Bug
