Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-07, with the labels that each got.

#1444 Code smell changes
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminGetrankCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetSpawnPointCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/DefaultAdminCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/blueprints/AdminBlueprintCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/blueprints/AdminBlueprintRenameCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/DefaultPlayerCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandBanlistCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/flags/Flag.java
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/api/user/User.java
  src/main/java/world/bentobox/bentobox/blueprints/Blueprint.java
  src/main/java/world/bentobox/bentobox/blueprints/BlueprintPaster.java
  src/main/java/world/bentobox/bentobox/commands/BentoBoxVersionCommand.java
  src/main/java/world/bentobox/bentobox/commands/reload/BentoBoxReloadLocalesCommand.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/objects/Table.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/yaml/ConfigHandler.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/LecternListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/PaperExperiencePickupListener.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/main/java/world/bentobox/bentobox/managers/FlagsManager.java
  src/main/java/world/bentobox/bentobox/managers/LocalesManager.java
  src/main/java/world/bentobox/bentobox/managers/WebManager.java
  src/main/java/world/bentobox/bentobox/managers/island/NewIsland.java
  src/main/java/world/bentobox/bentobox/util/ItemParser.java
  src/main/java/world/bentobox/bentobox/util/Util.java
  src/main/java/world/bentobox/bentobox/util/heads/HeadCache.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/purge/AdminPurgeUnownedCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandBanCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommandTest.java
  src/test/java/world/bentobox/bentobox/api/panels/PanelTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/protection/BreakBlocksListenerTest.java
Labels: Status: Done, Type: Enhancement

#1446 Rework PlayerHead Getter.
  pom.xml
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/util/heads/HeadCache.java
  src/main/java/world/bentobox/bentobox/util/heads/HeadGetter.java
  src/main/resources/config.yml
Labels: Status: Done, Type: Enhancement, api

#1453 1.14.2
  pom.xml
  src/main/java/world/bentobox/bentobox/api/user/User.java
Labels: Critical
