Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-04, with the labels that each got.

#1256 Improved/Fixed experience pickup flag on Paper servers
  pom.xml
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/PaperExperiencePickupListener.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
Labels: Status: Done, Type: Enhancement

#1264 Improved description of Creeper griefing flag
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1266 Updated license dates in startup message
  src/main/resources/locales/cs.yml
  src/main/resources/locales/de.yml
  src/main/resources/locales/en-US.yml
  src/main/resources/locales/es.yml
  src/main/resources/locales/fr.yml
  src/main/resources/locales/it.yml
  src/main/resources/locales/ja.yml
  src/main/resources/locales/lv.yml
  src/main/resources/locales/ru.yml
  src/main/resources/locales/tr.yml
  src/main/resources/locales/zh-CN.yml
  src/main/resources/locales/zh-HK.yml
Labels: Status: Done, Type: Enhancement

#1259 Add %[gamemode]_on_island% placeholder
  src/main/java/world/bentobox/bentobox/lists/GameModePlaceholder.java
Labels: Status: Done, Type: Enhancement

#1263 Add break-spawner flag
  src/main/java/world/bentobox/bentobox/listeners/flags/protection/BreakBlocksListener.java
  src/main/java/world/bentobox/bentobox/lists/Flags.java
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1267 Added coop and trust limits (with permissions)
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommand.java
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1278 Adds a single character prefix to database tables
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/commands/BentoBoxMigrateCommand.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/objects/DataObject.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabaseHandler.java
  src/main/resources/config.yml
  src/test/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseHandlerTest.java
Labels: Status: Need review, Type: Enhancement

#1285 Fixed BentoBox not properly disabling if errors at startup
  src/main/java/world/bentobox/bentobox/BentoBox.java
Labels: Status: Done, Type: Enhancement

#1289 Update Polish translation
  src/main/resources/locales/pl.yml
Labels: Status: Done, Type: Enhancement

#1301 Adds API to enable commands to be hidden from help and tab
  src/main/java/world/bentobox/bentobox/api/commands/CompositeCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/DefaultHelpCommand.java
  src/test/java/world/bentobox/bentobox/api/commands/HiddenCommandTest.java
Labels: Status: Done, Type: Enhancement, api

#1299 Implement ability to change PanelItem amount.
  src/main/java/world/bentobox/bentobox/api/panels/PanelItem.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelItemBuilder.java
Labels: Status: Done, Type: Enhancement

#1298 Enables UUIDs to be used in admin commands as well as names
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminDeleteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminGetrankCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminInfoCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetrankCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSwitchtoCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminTeleportCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminUnregisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminWhyCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/deaths/AdminDeathsAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/deaths/AdminDeathsRemoveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/deaths/AdminDeathsResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/deaths/AdminDeathsSetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeRemoveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeSetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/resets/AdminResetsAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/resets/AdminResetsRemoveCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/resets/AdminResetsResetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/resets/AdminResetsSetCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamDisbandCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamKickCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamSetownerCommand.java
  src/main/java/world/bentobox/bentobox/util/Util.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminDeleteCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminGetrankCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminInfoCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminSetrankCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminTeleportCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminUnregisterCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeDisplayCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeResetCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeSetCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamAddCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamDisbandCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamKickCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/team/AdminTeamSetownerCommandTest.java
Labels: Status: Done, Type: Enhancement

#1295 Add AdminSetSpawnPointCommand to change an island's spawn point
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetSpawnPointCommand.java
  src/main/resources/locales/en-US.yml
Labels: Status: Done, Type: Enhancement

#1302 Added Addon#reloadConfig()
  src/main/java/world/bentobox/bentobox/api/addons/Addon.java
Labels: Status: Done, Type: Enhancement, api

#1293 Add DefaultPlayerCommand and DefaultAdminCommand
  src/main/java/world/bentobox/bentobox/api/commands/admin/DefaultAdminCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/DefaultPlayerCommand.java
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
Labels: Status: Done, Type: Enhancement

#1308 Adds saveObjectAsync with a CompletableFuture return for databases
  src/main/java/world/bentobox/bentobox/database/AbstractDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/Database.java
  src/main/java/world/bentobox/bentobox/database/json/JSONDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/SQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/sql/sqlite/SQLiteDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/transition/TransitionDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandler.java
  src/main/java/world/bentobox/bentobox/managers/IslandDeletionManager.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/PlayersManager.java
  src/test/java/world/bentobox/bentobox/database/DatabaseTest.java
  src/test/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandlerTest.java
Labels: Status: Done, Type: Enhancement, api

#1305 Implements placeholder permissions for addons
  src/main/java/world/bentobox/bentobox/api/addons/AddonClassLoader.java
  src/main/java/world/bentobox/bentobox/api/addons/AddonDescription.java
  src/main/java/world/bentobox/bentobox/managers/AddonsManager.java
  src/test/java/world/bentobox/bentobox/managers/AddonsManagerTest.java
Labels: Status: Done, Type: Enhancement, api
