Repository BentoBoxWorld/BentoBox, pull requests merged in 2020-03, with the labels that each got.

#1206 Implement option to enable SSL for database connections.
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/database/DatabaseConnectionSettingsImpl.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/mongodb/MongoDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/mariadb/MariaDBDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/mysql/MySQLDatabaseConnector.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabase.java
  src/main/java/world/bentobox/bentobox/database/sql/postgresql/PostgreSQLDatabaseConnector.java
  src/main/resources/config.yml
Labels: Type: Enhancement

#1225 Improve bStats playersPerServer chart
  pom.xml
  src/main/java/world/bentobox/bentobox/BStats.java
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/Settings.java
Labels: Status: Done, Type: Enhancement

#1230 Fixes potion splash pvp check
  src/main/java/world/bentobox/bentobox/listeners/flags/settings/PVPListener.java
Labels: Status: Done, Type: Bug

#1251 Fixed player-not-cooped message key
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamUncoopCommand.java
Labels: Status: Done, Type: Bug
