Repository BentoBoxWorld/BentoBox, pull requests merged in 2021-03, with the labels that each got.

#1689 Switch to island homes from player homes.
  src/main/java/world/bentobox/bentobox/api/commands/admin/conversations/NamePrompt.java
  src/main/java/world/bentobox/bentobox/api/commands/island/CustomIslandMultiHomeHelp.java
  src/main/java/world/bentobox/bentobox/api/commands/island/DefaultPlayerCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandDeletehomeCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandGoCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandRenamehomeCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandSethomeCommand.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/IslandRespawnListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleport.java
  src/main/resources/locales/en-US.yml
  src/test/java/world/bentobox/bentobox/api/commands/island/CustomIslandMultiHomeHelpTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/IslandSethomeCommandTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/IslandRespawnListenerTest.java
  src/test/java/world/bentobox/bentobox/managers/IslandsManagerTest.java
  src/test/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleportBuilderTest.java
  src/test/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleportTest.java
Labels: Type: Enhancement

#1671 rework on Vietnamese translation
  src/main/resources/locales/vi.yml
Labels: Status: In progress, Type: Enhancement

#1693 Added LangUtils support.
  pom.xml
  src/main/java/world/bentobox/bentobox/BentoBox.java
  src/main/java/world/bentobox/bentobox/hooks/LangUtilsHook.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoMobLimitTab.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListener.java
  src/main/java/world/bentobox/bentobox/panels/BlueprintManagementPanel.java
  src/main/resources/plugin.yml
Labels: Type: Enhancement

#1714 zh-CN format optimization.
  src/main/resources/locales/zh-CN.yml
Labels: Type: Translation

#1717 Fixes a bug with end platform generation
  src/main/java/world/bentobox/bentobox/listeners/PortalTeleportationListener.java
Labels: Type: Bug
