Repository BentoBoxWorld/BentoBox, pull requests merged in 2021-02, with the labels that each got.

#1597 Nether portals
  src/main/java/world/bentobox/bentobox/api/configuration/WorldSettings.java
  src/main/java/world/bentobox/bentobox/listeners/PlayerEntityPortalEvent.java
  src/main/java/world/bentobox/bentobox/listeners/PortalTeleportationListener.java
  src/test/java/world/bentobox/bentobox/listeners/PortalTeleportationListenerTest.java
Labels: Status: In progress, Type: Enhancement

#1659 Decouple island location from island center.
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminDeleteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetProtectionCenterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSetspawnCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminUnregisterCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/DefaultAdminCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeAddCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeDisplayCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeSetCommand.java
  src/main/java/world/bentobox/bentobox/api/localization/TextVariables.java
  src/main/java/world/bentobox/bentobox/blueprints/BlueprintPaster.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/database/objects/IslandDeletion.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListener.java
  src/main/java/world/bentobox/bentobox/lists/GameModePlaceholder.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/util/DeleteIslandChunks.java
  src/main/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleport.java
  src/main/resources/locales/en-US.yml
  src/main/resources/plugin.yml
  src/test/java/world/bentobox/bentobox/TestBentoBox.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminRegisterCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/AdminUnregisterCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/admin/range/AdminRangeSetCommandTest.java
  src/test/java/world/bentobox/bentobox/database/objects/IslandDeletionTest.java
  src/test/java/world/bentobox/bentobox/database/yaml/YamlDatabaseHandlerTest.java
  src/test/java/world/bentobox/bentobox/listeners/JoinLeaveListenerTest.java
  src/test/java/world/bentobox/bentobox/listeners/flags/worldsettings/InvincibleVisitorsListenerTest.java
  src/test/java/world/bentobox/bentobox/util/teleport/SafeSpotTeleportBuilderTest.java
Labels: Type: Enhancement

#1682 Enables panels to know the context of the world that initiated them.
  src/main/java/world/bentobox/bentobox/api/commands/admin/AdminSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/IslandSettingsCommand.java
  src/main/java/world/bentobox/bentobox/api/panels/Panel.java
  src/main/java/world/bentobox/bentobox/api/panels/TabbedPanel.java
  src/main/java/world/bentobox/bentobox/api/panels/builders/PanelBuilder.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandCycleClick.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/CommandRankClickListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoLimitClickListener.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoMobLimitTab.java
  src/main/java/world/bentobox/bentobox/listeners/flags/clicklisteners/MobLimitClickListener.java
  src/main/java/world/bentobox/bentobox/panels/settings/SettingsTab.java
  src/test/java/world/bentobox/bentobox/listeners/flags/clicklisteners/GeoMobLimitTabTest.java
Labels: Type: Enhancement, api

#1679 Implements ability to use faster player head gatherer
  src/main/java/world/bentobox/bentobox/Settings.java
  src/main/java/world/bentobox/bentobox/util/heads/HeadGetter.java
  src/main/resources/config.yml
Labels: Type: Enhancement

#1691 Adds maxMembers to the Island object for persistent storage
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteAcceptCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommand.java
  src/main/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommand.java
  src/main/java/world/bentobox/bentobox/database/objects/Island.java
  src/main/java/world/bentobox/bentobox/listeners/JoinLeaveListener.java
  src/main/java/world/bentobox/bentobox/managers/IslandsManager.java
  src/main/java/world/bentobox/bentobox/managers/RanksManager.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamCoopCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamInviteCommandTest.java
  src/test/java/world/bentobox/bentobox/api/commands/island/team/IslandTeamTrustCommandTest.java
  src/test/java/world/bentobox/bentobox/listeners/JoinLeaveListenerTest.java
  src/test/java/world/bentobox/bentobox/managers/IslandsManagerTest.java
Labels: Type: Bug, Type: Enhancement
